### ISSUE TITLE
Create SingleProduct.js

### ISSUE THREAD

**Issue by DonnyDunamis** [2110-FTB-PT/troubleshooters#113]
Story:
  As a developer, I want a reusable component that renders out a single product in our ideal format that I can plug and place 
  where is appropriate throughout my react app.

  As a user, I want to be able to see information related to the product I am viewing and be able to add it to my cart should I 
  desire.

  As an admin, I want to be able to click a button to delete or edit a product.

Implementation:
  - [x] create my SingleProduct react component
  - [x] properly store my state at the correct level (probably want our product state stored at the app level)
  - [x] render out the information for a single product
    - do we want a more and less detailed view? less detailed for all products view more detailed for single?
    - if so, do we do this via conditional rendering or a separate component..
