### ISSUE TITLE
Product "card"

### ISSUE THREAD

**Issue by alancuenca** [2110-FTB-PT/troubleshooters#123]
Story:
As a developer I would like to have each product on a "card" to display that item's information and album cover

- [ ]create a card component

- [x] bring in a single product information to display on the card component i.e.: title, price, genre, add to cart

- [x] give the card css styling
