### ISSUE TITLE
create cart w/ products in seedData

### ISSUE THREAD

**Issue by alancuenca** [2110-FTB-PT/troubleshooters#63]
Story:
As a developer i want to have a functioning dummy cart that can be worked on without having an "add to cart" function built out.

- [ ] have a dummy cart in seedData
- [ ] add dummy products to user's cart
- [ ] display individual product prices
- [ ] display running total for products

**Comment by alancuenca** [comment]
Redundant issue. Matthew has this table taken care of in seedData
