### ISSUE TITLE
create products api routes that access information from database

### ISSUE THREAD

**Issue by scburkha005** [2110-FTB-PT/troubleshooters#8]
Story:
  As a front-end developer, I want api routes that will allow me to pull, update, create, and delete information for my products 
  in a meaningful way.

Implementation:
  - [x] GET /api/products for all products
  - [x] GET /api/products/:productId for a single product
  - [x] GET /api/products/categories/:categoryId for all products related to a single category
  - [x] POST /api/products to create a single product
  - [x] PATCH /api/products/:productId to update a single product
  - [x] DELETE /api/products/:productId to delete a product and all related table references
